### ISSUE TITLE
Stuck on loading data

### ISSUE THREAD

**Issue by Strosel** [siilisolutions-pl/room-booking-app#1] opened 2018-07-04 09:40 UTC
when I run `rba dev <config>` and the page loads it stops at "Loading data..." and throws these errors in console:

```
warning.js:33 Warning: Failed prop type: Invalid prop `rooms` of type `object` supplied to `RoomsSetup`, expected `array`.
    in RoomsSetup (created by Connect(RoomsSetup))
    in Connect(RoomsSetup) (created by Main)
    in div (created by Main)
    in Main (created by Connect(Main))
    in Connect(Main)
    in Provider
    in AppContainer
```
and
```
Uncaught TypeError: rooms.map is not a function
    at RoomSelection (RoomSelection.js:16)
    at StatelessComponent.render (ReactCompositeComponent.js:44)
    at ReactCompositeComponent.js:795
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:794)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:821)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:745)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:723)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:644)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:546)
```

I can't really figure out whats wrong. Any thoughts?

**Comment by tjankowski** [comment] 2018-07-12 12:57
Hi @Strosel,
Could you share logs from running `rba dev` command and if that is possible your config.json file?

**Comment by tjankowski** [comment] 2019-06-04 13:12
Hi @Strosel, I would like to close this issue. I was not able to reproduce your issue. Let me know if the problem still occurs.

**Closed** 2019-06-04 18:39 UTC
